### ISSUE TITLE
Anomaly detection

### ISSUE THREAD

**Issue by jkowall** [dgarros/netdevops-survey#11]
The anomaly detection question is confusing. None of these products actually do anomaly detection. You'd need something in the monitoring space, or at least some custom tooling which uses machine learning, threshold management, etc. Please clarify.

**Comment by dgarros** [comment]
@jkowall good point, what would you propose ?

**Comment by jkowall** [comment]
So your options for anomaly detection are really:

- Commercial 3rd party Monitoring Products (there are just too many to list here)
- Commercial Configuration Management (you didn't include any of those aside from vendor tools, what about NCCM type tools?)
- Commercial machine learning (AIOps, ITOA) (event correlation, textual/log analytics)
- Open Source Monitoring
- Open Source Configuration Management (where 90% of the current choices are)
- Open Source Analytics (toolkits for AI/ML, many many to list here)
- Homegrown Analytics based on Open Source

Finally, why did we put stackstorm instead of the other 300 companies who do the same thing? Zapier, Integromat, or another 500 of the same tool :)

**Comment by dgarros** [comment]
@jkowall sorry for the delayed response
In my mind the goal of the survey is not to oppose Open source and Commercial solutions but rather to understand what "generation" of tools people are using.
It's not easy to classify the different type of tools and solutions out there, what do you think of the following list to describe the different type of anomaly detection out-there ?
- Threshold based alert
- Single Event based alert (interface down)
- Multi Event/Data correlation engine (custom logic)
- Multi Event/Data correlation engine using AI/ML
- Proactive alert based using AI/ML

I can actually think of more dimensions but it's hard to describe all of them
Maybe we should split the question and have multiple questions for anomaly detection.

**Comment by jkowall** [comment]
The problem is that there is no explanation of the use cases or outcomes you are using the anomaly detection for. If you put this into the category of what data they are applying to it helps:

- Performance monitoring
- Device monitoring
- Device configuration changes
- Network status changes (routing, or other)

What else am I missing? Then for each of these, you can your list interlaced within each. Alternately we can focus on the use cases, meaning what is the user trying to do (one or more).

- Plan a forthcoming change
- Make a change to fulfill a request
- Make a change to fix an issue
- Detect an issue
- Solve a problem
- Prevent a problem
- Plan an upgrade or migration
- Analyze data for another use case

**Comment by fracaen** [comment]
Discussed in real time, and turned into a PR.
