### ISSUE TITLE
Troubleshooting Quesiton

### ISSUE THREAD

**Issue by jkowall** [dgarros/netdevops-survey#12]
When you think about troubleshooting, you need a combination of diagnostic tools, monitoring/telemetry, and configuration tracking tools. Since no one has built a real cross platform workflow tool to help on this path the engineer ends up looking at all the evidence to troubleshoot and isolate. 

I do not think we've set this question up correctly considering that we are only looking at the configuration, which is only a small part of the issue.

**Comment by fracaen** [comment]
Thank you, this is worth exploring, please submit the wording you're thinking about in a PR :-)

**Comment by fracaen** [comment]
Discussed in real time, and turned into a PR. Deleting this question

**Comment by jkowall** [comment]
We removed question as it was confusing.
