### ISSUE TITLE
2019 Clean Responses - Which solution are you using to run virtual network devices for training or qualification purposes?

### ISSUE THREAD

**Issue by dgarros** [dgarros/netdevops-survey#30]

**Comment by fracaen** [comment]
Removed commas:
Non-VMWare hypervisor (KVM, et al.) -> Non-VMWare hypervisor (KVM et al.)
Vendor provided solution (VIRL, Junosphere .. ) -> Vendor provided solution (VIRL / Junosphere .. )

Merged a couple VIRL replies into Vendor provided solution (VIRL / Junosphere .. )

L229-231 none -> We are not using   virtual network devices for training or qualification

L119-120 Replaced mentions of real hardware with We are not using virtual network devices for training or qualification

L140 homerolled -> Homemade solution
