### ISSUE TITLE
Suggestions for 2019 questionnaire

### ISSUE THREAD

**Issue by nickrusso42518** [dgarros/netdevops-survey#4]
These are general comments/suggestions. I didn't want to create an issue for each one as I felt it would be sloppy for such micro-focused discussion points.

# ---

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L29

Microsoft Excel should be an option here, because it is extremely common in Government organizations and also some SMBs.

# ---

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L51

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L93

I see we list `napalm`, but that's a Python package. Do other packages like `netmiko` and `nornir` count as "custom scripts"? Or do these qualify as their own "solutions"? We might want to say:
  - "Low level custom scripts (Python paramiko/socket)
  - "Custom scripts using common libraries (netmiko/napalm)
  - "Nornir" (yes, I think `nornir` should be its own choice if `ansible` is also a choice)

# ---

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L158

We should either say "Service Provider" by itself and remove "backbone", or add "Service Provider edge". I spent years working at a Government SP where we *only* automated edge service provisioning and not core activity. Many SPs separate their core and edge teams so it is entirely possible that an SP edge engineer pencils in a custom entry, which probably confuses the measurement.

# ---

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L167

We should add "Bash" as this is still a common component in integrated automation systems today.

**Comment by dgarros** [comment]
Thanks a lot @nickrusso42518, great inputs
I tried to incorporate everything in #8 please can you take a look

**Comment by dgarros** [comment]
Closing since #8 has been merged 
Thanks a lot @nickrusso42518 for your inputs
