### ISSUE TITLE
Suggestion to Survey

### ISSUE THREAD

**Issue by skg-net** [dgarros/netdevops-survey#5]
@all if every one is okay with the suggestion, let me know I can go ahead and address them.

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L27
- can we have a text box option here to cover the other use cases which are not covered. It will help us in identifying other use case people try to solve.

https://github.com/dgarros/netdevops-survey/blob/2a1f310dcb810bc429a842684e58877cbfa82551/questionnaire/2019/questions.yaml#L38
- need to work on the flow of question in the survey.

**Comment by fracaen** [comment]
Hi @skg-net and thanks for participating!
When this survey was first run in 2016 by @dgarros , they had text box options. It seemed like a good idea at the time, but resulted in a ton of manual labor to sort through the replies. So we're taking a different (and admittedly lazier) approach this time: get all the answer options in **now**, during the questionnaire definition phase. And no text-boxes to add options during the survey proper.
I'll let @dgarros correct me / add to this if I didn't relay his 2016 experience properly. In the meantime, please keep adding to the questionnaire!

**Comment by skg-net** [comment]
@fracaen sure, just started reviewing the questionnaire, I will add my feedback in this thread itself. once agreed will fix them and raise a PR. I'm aware of the pain it caused @dgarros but we will miss significant data if this option is not provided. I can take the responsibility of sorting that out and publishing it.

**Comment by dgarros** [comment]
@skg-net if you are volunteer to clean up all the answers, I'm good with adding the field back

**Comment by dgarros** [comment]
The changes have been made in #8
