### ISSUE TITLE
Change repo's social media preview

### ISSUE THREAD

**Issue by fracaen** [dgarros/netdevops-survey#6]
Nothing against your mugshot @dgarros but maybe replace it with a simple image?
https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview

For example, and I have zero artistic talent:
![2019 netdevops survey logo 001](https://user-images.githubusercontent.com/23023479/65127154-0dc30e00-d9ac-11e9-89d3-75366b1c40fb.png)

**Comment by dgarros** [comment]
Done, I didn't knew it was even possible
let me know if you would like to change the picture
![NetDevOps Suvey](https://user-images.githubusercontent.com/304126/65149803-ca3ec300-d9f0-11e9-8c2f-b1a550536705.png)
