### ISSUE TITLE
Leadership Support Level

### ISSUE THREAD

**Issue by jvanderaa** [dgarros/netdevops-survey#61]
I wanted to write this down before I forgot, and still need to see if there is a question out there for this. A gauge of leadership support level.

## What level of support do you have to introduce new Knowledge, Skills, Abilities, and tooling into your environment?

- [ ] It is actively frowned upon
- [ ] Anything that is done is done covertly until proven successful
- [ ] It takes a back seat to production fires or projects
- [ ] It is actively being developed and discussed routinely

**Comment by abenokraitis** [comment]
maybe something like "Does your IT organization have a formal and/or sponsored initiatives in place to expand and improve the use of automation on the network?" Answers could be 1) Yes, this is critical to the top-level IT strategy (proactive); 2) Yes, but is only when convenient (reactive); 3) No, I'm doing it without leadership's buy-in to make my job easier

**Comment by dgarros** [comment]
I think it would be great to have a question like that
I tried to combine both proposals in #67, I hope I captured your ideas correctly please review and let me know

**Comment by abenokraitis** [comment]
Looks great!

**Comment by dgarros** [comment]
Closing this one since the PR was merged
