### ISSUE TITLE
Potential new questions for 2020 survey

### ISSUE THREAD

**Issue by abenokraitis** [dgarros/netdevops-survey#62]
1) What is your primary role within your technology organization?
- Network Administrator / Operator
- Network Architect / Engineer
- Software Engineer / Developer
- Cloud Engineer
- System Administrator
- Project or Program Manager
- IT Manager / Decision Maker

2) What connection methods / transports are being utilized as part of your network automation implementation? (Select all that apply, multi-selection)
- CLI
- NETCONF
- RESTCONF
- GRPC
- HTTP

3) What is the primary network automation strategy used currently in your organization? (Where are you now?)
(Pick one only)
- No automation currently
- Existing and well known platform-specific CLI commands are sent over via scripts/playbooks by humans
- Existing and well known platform-specific CLI commands are sent over via scripts/playbooks but kicked off by an orchestration solution via APIs (Jenkins, AWX/Tower)
- Configurations are templated (for example Jinja) and stored in source control
- Configurations are parsed and converted/normalized to key-value pairs and stored in source control

4) What is your desired network automation strategy for the future? (Where do you want to be?)
(pick one only)
same as above

5) What is your current "source of truth" for network configurations?
(pick one only)
- The configuration on the actual device (requires pulling the config before modifying it)
- Many "golden masters" off the device, platform-specific in source control
- One (or few) "golden master" off the device, platform-agnostic in source control
- Generic key-value pairs off the devices in a database or source control 

6) Are your requirements network automation influenced by other IT teams in your organization? That is, are you looking into integrating with other types of endpoints? If so please select other technologies you may have to  integrate with (as part of a CI/CD or complex workflow process).
(select all that apply)
- Kubernetes / Containers
- Clouds
- Windows Servers
- Linux Servers
- Nope, network only

**Comment by abenokraitis** [comment]
Since the survey is heavily focused on the "how" and what tools are used, tried to leverage and lead with that with these new questions.

**Comment by dgarros** [comment]
Thanks a lit @abenokraitis for all your inputs and suggestions

I think Q1 and Q2 are great, I already opened some PRs for them and I propose to move the discussion in their respective PR

for Q3 & Q4, I'm not sure if it's possible to create an exhaustive list of responses to these questions, also the current list is very configuration deployment focused. 

For Q5, I agree we are missing a question (or maybe more) about SOT. I'll start a new issue just for that because i think it's worth having a separate thread for that

and I think Q6 is great

**Comment by abenokraitis** [comment]
Sounds great, thanks for the consideration!
