### ISSUE TITLE
Ask more information about the Source of Truth for the network

### ISSUE THREAD

**Issue by dgarros** [dgarros/netdevops-survey#69]
I think it would be great to capture more information regarding the Source of Truth for the network.  
@abenokraitis proposed some ideas in #62 as well.

In addition to "what is your current SOT", it would be interesting to understand 
- How the SOT has been populated (manually, automatically)
  - for greenfield deployment
  - for brownfield deployment
- How many systems are composing the SOT
- What level of information is currently stored in the SOT (this one might be a bit too advanced)

**Comment by abenokraitis** [comment]
Just brainstorming:

1) What is your "source of truth?" a) What's a source of truth? It's our dude, Jerry. b) spreadsheets c) an open source CMDB (like netbox) d) an enterprise CMDB (like SNOW or Infoblox) e) homegrown database/implementation

2) Does the network team integrate with other teams for inventory management? a) yes b) no

**Comment by dgarros** [comment]
I opened #74 and #75 based on the conversation on Slack few days ago.
