### ISSUE TITLE
Merge "Low level custom scripts" and "Custom scripts using common libraries"

### ISSUE THREAD

**Issue by dgarros** [dgarros/netdevops-survey#70]
Last year we decided to split the option `Custom scripts (python ..)` into 2 separate options :
    - Low level custom scripts (Python paramiko/socket)
    - Custom scripts using common libraries (netmiko/napalm)

I think this split made the responses harder to read and understand without providing additional value so my proposal is to merge them back into `Custom scripts` or similar this year.

**Comment by abenokraitis** [comment]
Maybe it's better to ask something like:
- Low level custom scripts ("stock" Python package itself, bash)
- Custom scripts with add-on libraries (Python + netmiko, napalm, nornir, etc.)
- Applications built on top of or that requires Python (Ansible)

**Comment by dgarros** [comment]
Another idea is we could convert that into 2 options:
- `Internally developed scripts`
- `Another open source project (not listed above)`

**Comment by fracaen** [comment]
PR merged
