### ISSUE TITLE
Survey feedback

### ISSUE THREAD

**Issue by nickrusso42518** [dgarros/netdevops-survey#76]
Excellent questions. Only one minor comment to provide clarity:

https://github.com/dgarros/netdevops-survey/blob/8cf453e774b26cbae5d13d8e4d283a966416e53d/questionnaire/2020/questions.yaml#L251

Since RESTCONF is already an option, I would recommend we change `HTTP/HTTPS` to `Non-Restconf HTTP/HTTPS` for clarity. Some products have web-based GUIs or basic HTTP APIs that don't involve YANG at all (IOS-XE had a legacy REST API for example). I assume that is what this option is meant to represent.

**Comment by dgarros** [comment]
Thanks @nickrusso42518 , I opened a PR to fix that

**Comment by fracaen** [comment]
Approved and merged. If we wanted to be even more specific, we could also add "non-netconf" to the ssh option...
