### ISSUE TITLE
possible question to idenfity scope of automation

### ISSUE THREAD

**Issue by dpnetca** [dgarros/netdevops-survey#9]
I stuck a comment in slack, but adding it here as well.  I am thinking it would be good to see how automation is used in different roles (managing a single organization network (be it SMB, Enterprise, SP, etc.) or as a consultant automating specific tasks, or help customers build automation, or Managing multiple separate organizations, etc.

Something along the lines of:

- title: In what scope do you use network automation?
  type: Multiple Choice
  responses:
  - Single Organization (SMB, Large Enterprise, Service Provider, etc.)
  - Consultant automating repetitive consulting tasks across multiple client organizations on a per engagement basis
  - Consultant assisting organizations to develop implement network automation
  - Managing multiple organization networks (i.e. MSP)

**Comment by dpnetca** [comment]
note I left this as multiple choice not single choice simply as my role potentially hits two those (I am working on both the 2nd and 4th options at the moment)

**Comment by fracaen** [comment]
Thank you @dpnetca . Let me take a stab at it.

**Comment by fracaen** [comment]
Please review this @dpnetca 
https://github.com/dgarros/netdevops-survey/pull/17
